### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lilicocon** [dom0ng/pcileech-wifi-v2#2]
Hello, according to the description in your unknown post, I purchased the network card shown in the post. I changed the corresponding parameters in the source code. After compiling and flashing, it cannot be used normally. There is an exclamation mark, and the speed cannot be measured. Mine is cap 75t.

**Comment by dom0ng** [comment]
> Hello, according to the description in your unknown post, I purchased the network card shown in the post. I changed the corresponding parameters in the source code. After compiling and flashing, it cannot be used normally. There is an exclamation mark, and the speed cannot be measured. Mine is cap 75t.

You need to remove the magic lock.
