### ISSUE TITLE
 Vmm

### ISSUE THREAD

**Issue by 1Nixyy** [dom0ng/pcileech-wifi-v2#3]
[i] Vmm Version: 5.8.5.124
[i] Leechcore Version: 2.16.2.53
DEVICE: FPGA: Enigma X1 PCIe gen1 x1 [250,10,500] [v4.13,0700] [ASYNC,NORM]
FPGA: TINY PCIe TLP algrithm auto-selected!
[CORE]     Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system.
         Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.
         If arm64 dump, specify architecture: -arch arm64
[CORE]     Failed to initialize.

[CORE]     SHUTDOWN COMPLETED (000002B3DEF00040).
[CORE]       TIME: 2024-11-23 21:56:24 UTC.
[CORE]       RUNTIME: 0s.

[FAIL] VMM INIT FAILED.
Press any key to continue.

**Comment by dom0ng** [comment]
You need to activate it remove the lock.

**Comment by suixin1424** [comment]
how to achieve it ?

**Comment by suixin1424** [comment]
i solved it. The secret command code is 0x0000010500000050
